apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-sentinel-svc
    role: service
  name: redis-sentinel
  namespace: {{ redis_namespace }}
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    redis-role: "sentinel"