apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-sentinel
  namespace: {{ redis_namespace }}
spec:
  replicas: {{ redis_sentinel_replicas }}
  template:
    metadata:
      labels:
        app: "redis"
        name: redis-sentinel
    spec:
{% if redis_node_selector | default({}) %}
      nodeSelector:
        {{ redis_node_selector | to_nice_yaml | indent(8) }}
{% endif %}
      containers:
        - name: sentinel
          image: {{ redis_image }}
          resources:
            {{ redis_sentinel_resources | to_nice_yaml(indent=2) | indent(12) }}
          env:
            - name: SENTINEL
              value: "true"
            - name: REDIS_CHART_PREFIX
              value: redis-
          ports:
            - containerPort: 26379