
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: redis-server
  namespace: {{ redis_namespace }}
  labels:
    app: "redis"
    name: "redis-server"
    redis-node: "true"
spec:
  replicas: {{ redis_server_replicas }}
  serviceName: redis-server
  template:
    metadata:
      labels:
        app: "redis"
        name: "redis-server"
        redis-node: "true"
    spec:
{% if redis_node_selector | default({}) %}
      nodeSelector:
        {{ redis_node_selector | to_nice_yaml | indent(8) }}
{% endif %}
      containers:
        - name: redis
          image: {{ redis_image }}
          resources:
            {{ redis_server_resources | to_nice_yaml(indent=2) | indent(12) }}
          env:
            - name: REDIS_SENTINEL_SERVICE_HOST
              value: "redis-sentinel"
            - name: REDIS_CHART_PREFIX
              value: redis-
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /redis-master-data 
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ redis_persistent_volume_size }}
        selector:
          matchLabels:
            type: local
            app: redis