apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-ha-sentinel-svc
    role: service
  name: redis-ha-sentinel
  namespace: {{ redis_ha_namespace }}
spec:
  ports:
    - port: 26379
      targetPort: 26379
  selector:
    redis-role: "sentinel"